import { __ } from '@wordpress/i18n';

export const academyContainerVariations = [
	{
		name: 'academy-default',
		title: __( '1 column', 'ablocks' ),
		description: __(
			'Preset academy container with flex layout and default attributes.',
			'ablocks'
		),
		icon: <span className="ablocks-icon ablocks-icon--column-1"></span>,
		attributes: {
			variationSelected: true,
			blockVersion: 2,
			containerWidth: {
				value: 700,
				valueTablet: '',
				valueMobile: '',
				valueUnit: 'px',
				valueUnitTablet: '',
				valueUnitMobile: '',
			},
			floatAlignment: {
				value: 'left',
				valueTablet: '',
				valueMobile: '',
			},
			floatMargin: {
				isLinked: true,
				isLinkedTablet: true,
				isLinkedMobile: true,
				common: '',
				top: '',
				right: '',
				bottom: '',
				left: '50',
				unit: 'px',
				commonTablet: '',
				topTablet: '',
				rightTablet: '',
				bottomTablet: '',
				leftTablet: '',
				unitTablet: '',
				commonMobile: '',
				topMobile: '',
				rightMobile: '',
				bottomMobile: '',
				leftMobile: '',
				unitMobile: '',
			},
		},
		innerBlocks: [
			[
				'ablocks/academy-container',
				{
					variationSelected: true,
					containerWidth: {
						value: 98,
						valueTablet: '',
						valueMobile: '',
						valueUnit: '%',
						valueUnitTablet: '',
						valueUnitMobile: '',
					},
					floatAlignment: {
						value: '',
						valueTablet: '',
						valueMobile: '',
					},
					floatMargin: {
						isLinked: true,
						isLinkedTablet: true,
						isLinkedMobile: true,
						common: '',
						top: '',
						right: '',
						bottom: '',
						left: '',
						unit: 'px',
						commonTablet: '',
						topTablet: '',
						rightTablet: '',
						bottomTablet: '',
						leftTablet: '',
						unitTablet: '',
						commonMobile: '',
						topMobile: '',
						rightMobile: '',
						bottomMobile: '',
						leftMobile: '',
						unitMobile: '',
					},
				},
			],
		],
		scope: [ 'block' ],
		isDefault: true,
	},
	{
		name: 'academy-default',
		title: __( '2 column', 'ablocks' ),
		description: __(
			'Preset academy container with flex layout and default attributes.',
			'ablocks'
		),
		icon: <span className="ablocks-icon ablocks-icon--column-2"></span>,
		attributes: {
			variationSelected: true,
			blockVersion: 2,
			containerWidth: {
				value: 349,
				valueTablet: '',
				valueMobile: '',
				valueUnit: 'px',
				valueUnitTablet: '',
				valueUnitMobile: '',
			},
			floatAlignment: {
				value: 'left',
				valueTablet: '',
				valueMobile: '',
			},
			floatMargin: {
				isLinked: true,
				isLinkedTablet: true,
				isLinkedMobile: true,
				common: '',
				top: '',
				right: '',
				bottom: '',
				left: '50',
				unit: 'px',
				commonTablet: '',
				topTablet: '',
				rightTablet: '',
				bottomTablet: '',
				leftTablet: '',
				unitTablet: '',
				commonMobile: '',
				topMobile: '',
				rightMobile: '',
				bottomMobile: '',
				leftMobile: '',
				unitMobile: '',
			},
		},
		innerBlocks: [
			[
				'ablocks/academy-container',
				{
					variationSelected: true,
					containerWidth: {
						value: 98,
						valueTablet: '',
						valueMobile: '',
						valueUnit: '%',
						valueUnitTablet: '',
						valueUnitMobile: '',
					},
					floatAlignment: {
						value: '',
						valueTablet: '',
						valueMobile: '',
					},
					floatMargin: {
						isLinked: true,
						isLinkedTablet: true,
						isLinkedMobile: true,
						common: '',
						top: '',
						right: '',
						bottom: '',
						left: '',
						unit: 'px',
						commonTablet: '',
						topTablet: '',
						rightTablet: '',
						bottomTablet: '',
						leftTablet: '',
						unitTablet: '',
						commonMobile: '',
						topMobile: '',
						rightMobile: '',
						bottomMobile: '',
						leftMobile: '',
						unitMobile: '',
					},
				},
				[
					[
						'ablocks/academy-container',
						{
							variationSelected: true,
							containerWidth: {
								value: 99,
								valueUnit: '%',
								valueTablet: '',
								valueMobile: '',
								valueUnitTablet: '',
								valueUnitMobile: '',
							},
							floatAlignment: {
								value: '',
								valueTablet: '',
								valueMobile: '',
							},
							floatMargin: {
								isLinked: true,
								isLinkedTablet: true,
								isLinkedMobile: true,
								common: '',
								top: '',
								right: '',
								bottom: '',
								left: '',
								unit: 'px',
								commonTablet: '',
								topTablet: '',
								rightTablet: '',
								bottomTablet: '',
								leftTablet: '',
								unitTablet: '',
								commonMobile: '',
								topMobile: '',
								rightMobile: '',
								bottomMobile: '',
								leftMobile: '',
								unitMobile: '',
							},
						},
					],
				],
			],
			[
				'ablocks/academy-container',
				{
					variationSelected: true,
					containerWidth: {
						value: 98,
						valueTablet: '',
						valueMobile: '',
						valueUnit: '%',
						valueUnitTablet: '',
						valueUnitMobile: '',
					},
					floatAlignment: {
						value: '',
						valueTablet: '',
						valueMobile: '',
					},
					floatMargin: {
						isLinked: true,
						isLinkedTablet: true,
						isLinkedMobile: true,
						common: '',
						top: '',
						right: '',
						bottom: '',
						left: '',
						unit: '%',
						commonTablet: '',
						topTablet: '',
						rightTablet: '',
						bottomTablet: '',
						leftTablet: '',
						unitTablet: '',
						commonMobile: '',
						topMobile: '',
						rightMobile: '',
						bottomMobile: '',
						leftMobile: '',
						unitMobile: '',
					},
				},
				[
					[
						'ablocks/academy-container',
						{
							variationSelected: true,
							containerWidth: {
								value: 99,
								valueUnit: '%',
								valueTablet: '',
								valueMobile: '',
								valueUnitTablet: '',
								valueUnitMobile: '',
							},
							floatAlignment: {
								value: '',
								valueTablet: '',
								valueMobile: '',
							},
							floatMargin: {
								isLinked: true,
								isLinkedTablet: true,
								isLinkedMobile: true,
								common: '',
								top: '',
								right: '',
								bottom: '',
								left: '',
								unit: 'px',
								commonTablet: '',
								topTablet: '',
								rightTablet: '',
								bottomTablet: '',
								leftTablet: '',
								unitTablet: '',
								commonMobile: '',
								topMobile: '',
								rightMobile: '',
								bottomMobile: '',
								leftMobile: '',
								unitMobile: '',
							},
						},
					],
				],
			],
		],
		scope: [ 'block' ],
		isDefault: true,
	},
	{
		name: 'academy-three-columns',
		title: __( '3 Columns', 'ablocks' ),
		description: __(
			'Preset academy container with three evenly sized inner containers.',
			'ablocks'
		),
		icon: <span className="ablocks-icon ablocks-icon--column-3"></span>,
		attributes: {
			variationSelected: true,
			blockVersion: 2,
			containerWidth: {
				value: 232,
				valueTablet: '',
				valueMobile: '',
				valueUnit: 'px',
				valueUnitTablet: '',
				valueUnitMobile: '',
			},
			floatAlignment: {
				value: 'left',
				valueTablet: '',
				valueMobile: '',
			},
			floatMargin: {
				isLinked: true,
				isLinkedTablet: true,
				isLinkedMobile: true,
				common: '',
				top: '0',
				right: '0',
				bottom: '0',
				left: '50',
				unit: 'px',
				commonTablet: '',
				topTablet: '',
				rightTablet: '',
				bottomTablet: '',
				leftTablet: '',
				unitTablet: '',
				commonMobile: '',
				topMobile: '',
				rightMobile: '',
				bottomMobile: '',
				leftMobile: '',
				unitMobile: '',
			},
		},
		innerBlocks: [
			[
				'ablocks/academy-container',
				{
					variationSelected: true,
					containerWidth: {
						value: 98,
						valueTablet: '',
						valueMobile: '',
						valueUnit: '%',
						valueUnitTablet: '',
						valueUnitMobile: '',
					},
					floatAlignment: {
						value: '',
						valueTablet: '',
						valueMobile: '',
					},
					floatMargin: {
						isLinked: true,
						isLinkedTablet: true,
						isLinkedMobile: true,
						common: '',
						top: '',
						right: '',
						bottom: '',
						left: '',
						unit: 'px',
						commonTablet: '',
						topTablet: '',
						rightTablet: '',
						bottomTablet: '',
						leftTablet: '',
						unitTablet: '',
						commonMobile: '',
						topMobile: '',
						rightMobile: '',
						bottomMobile: '',
						leftMobile: '',
						unitMobile: '',
					},
				},
				[
					[
						'ablocks/academy-container',
						{
							variationSelected: true,
							containerWidth: {
								value: 99,
								valueUnit: '%',
								valueTablet: '',
								valueMobile: '',
								valueUnitTablet: '',
								valueUnitMobile: '',
							},
							floatAlignment: {
								value: '',
								valueTablet: '',
								valueMobile: '',
							},
							floatMargin: {
								isLinked: true,
								isLinkedTablet: true,
								isLinkedMobile: true,
								common: '',
								top: '',
								right: '',
								bottom: '',
								left: '',
								unit: 'px',
								commonTablet: '',
								topTablet: '',
								rightTablet: '',
								bottomTablet: '',
								leftTablet: '',
								unitTablet: '',
								commonMobile: '',
								topMobile: '',
								rightMobile: '',
								bottomMobile: '',
								leftMobile: '',
								unitMobile: '',
							},
						},
					],
				],
			],
			[
				'ablocks/academy-container',
				{
					variationSelected: true,
					containerWidth: {
						value: 98,
						valueTablet: '',
						valueMobile: '',
						valueUnit: '%',
						valueUnitTablet: '',
						valueUnitMobile: '',
					},
					floatAlignment: {
						value: '',
						valueTablet: '',
						valueMobile: '',
					},
					floatMargin: {
						isLinked: true,
						isLinkedTablet: true,
						isLinkedMobile: true,
						common: '',
						top: '',
						right: '',
						bottom: '',
						left: '',
						unit: 'px',
						commonTablet: '',
						topTablet: '',
						rightTablet: '',
						bottomTablet: '',
						leftTablet: '',
						unitTablet: '',
						commonMobile: '',
						topMobile: '',
						rightMobile: '',
						bottomMobile: '',
						leftMobile: '',
						unitMobile: '',
					},
				},
				[
					[
						'ablocks/academy-container',
						{
							variationSelected: true,
							containerWidth: {
								value: 99,
								valueUnit: '%',
								valueTablet: '',
								valueMobile: '',
								valueUnitTablet: '',
								valueUnitMobile: '',
							},
							floatAlignment: {
								value: '',
								valueTablet: '',
								valueMobile: '',
							},
							floatMargin: {
								isLinked: true,
								isLinkedTablet: true,
								isLinkedMobile: true,
								common: '',
								top: '',
								right: '',
								bottom: '',
								left: '',
								unit: 'px',
								commonTablet: '',
								topTablet: '',
								rightTablet: '',
								bottomTablet: '',
								leftTablet: '',
								unitTablet: '',
								commonMobile: '',
								topMobile: '',
								rightMobile: '',
								bottomMobile: '',
								leftMobile: '',
								unitMobile: '',
							},
						},
					],
				],
			],
			[
				'ablocks/academy-container',
				{
					variationSelected: true,
					containerWidth: {
						value: 98,
						valueTablet: '',
						valueMobile: '',
						valueUnit: '%',
						valueUnitTablet: '',
						valueUnitMobile: '',
					},
					floatAlignment: {
						value: '',
						valueTablet: '',
						valueMobile: '',
					},
					floatMargin: {
						isLinked: true,
						isLinkedTablet: true,
						isLinkedMobile: true,
						common: '',
						top: '',
						right: '',
						bottom: '',
						left: '',
						unit: 'px',
						commonTablet: '',
						topTablet: '',
						rightTablet: '',
						bottomTablet: '',
						leftTablet: '',
						unitTablet: '',
						commonMobile: '',
						topMobile: '',
						rightMobile: '',
						bottomMobile: '',
						leftMobile: '',
						unitMobile: '',
					},
				},
				[
					[
						'ablocks/academy-container',
						{
							variationSelected: true,
							containerWidth: {
								value: 99,
								valueUnit: '%',
								valueTablet: '',
								valueMobile: '',
								valueUnitTablet: '',
								valueUnitMobile: '',
							},
							floatAlignment: {
								value: '',
								valueTablet: '',
								valueMobile: '',
							},
							floatMargin: {
								isLinked: true,
								isLinkedTablet: true,
								isLinkedMobile: true,
								common: '',
								top: '',
								right: '',
								bottom: '',
								left: '',
								unit: 'px',
								commonTablet: '',
								topTablet: '',
								rightTablet: '',
								bottomTablet: '',
								leftTablet: '',
								unitTablet: '',
								commonMobile: '',
								topMobile: '',
								rightMobile: '',
								bottomMobile: '',
								leftMobile: '',
								unitMobile: '',
							},
						},
					],
				],
			],
		],
		scope: [ 'block' ],
	},
	{
		name: 'academy-three-columns',
		title: __( '4 Columns', 'ablocks' ),
		description: __(
			'Preset academy container with three evenly sized inner containers.',
			'ablocks'
		),
		icon: <span className="ablocks-icon ablocks-icon--column-4"></span>,
		attributes: {
			variationSelected: true,
			blockVersion: 2,
			containerWidth: {
				value: 174,
				valueTablet: '',
				valueMobile: '',
				valueUnit: 'px',
				valueUnitTablet: '',
				valueUnitMobile: '',
			},
			floatAlignment: {
				value: 'left',
				valueTablet: '',
				valueMobile: '',
			},
			floatMargin: {
				isLinked: true,
				isLinkedTablet: true,
				isLinkedMobile: true,
				common: '',
				top: '0',
				right: '0',
				bottom: '0',
				left: '50',
				unit: 'px',
				commonTablet: '',
				topTablet: '',
				rightTablet: '',
				bottomTablet: '',
				leftTablet: '',
				unitTablet: '',
				commonMobile: '',
				topMobile: '',
				rightMobile: '',
				bottomMobile: '',
				leftMobile: '',
				unitMobile: '',
			},
		},
		innerBlocks: [
			[
				'ablocks/academy-container',
				{
					variationSelected: true,
					containerWidth: {
						value: 98,
						valueTablet: '',
						valueMobile: '',
						valueUnit: '%',
						valueUnitTablet: '',
						valueUnitMobile: '',
					},
					floatAlignment: {
						value: '',
						valueTablet: '',
						valueMobile: '',
					},
					floatMargin: {
						isLinked: true,
						isLinkedTablet: true,
						isLinkedMobile: true,
						common: '',
						top: '',
						right: '',
						bottom: '',
						left: '',
						unit: 'px',
						commonTablet: '',
						topTablet: '',
						rightTablet: '',
						bottomTablet: '',
						leftTablet: '',
						unitTablet: '',
						commonMobile: '',
						topMobile: '',
						rightMobile: '',
						bottomMobile: '',
						leftMobile: '',
						unitMobile: '',
					},
				},
				[
					[
						'ablocks/academy-container',
						{
							variationSelected: true,
							containerWidth: {
								value: 99,
								valueUnit: '%',
								valueTablet: '',
								valueMobile: '',
								valueUnitTablet: '',
								valueUnitMobile: '',
							},
							floatAlignment: {
								value: '',
								valueTablet: '',
								valueMobile: '',
							},
							floatMargin: {
								isLinked: true,
								isLinkedTablet: true,
								isLinkedMobile: true,
								common: '',
								top: '',
								right: '',
								bottom: '',
								left: '',
								unit: 'px',
								commonTablet: '',
								topTablet: '',
								rightTablet: '',
								bottomTablet: '',
								leftTablet: '',
								unitTablet: '',
								commonMobile: '',
								topMobile: '',
								rightMobile: '',
								bottomMobile: '',
								leftMobile: '',
								unitMobile: '',
							},
						},
					],
				],
			],
			[
				'ablocks/academy-container',
				{
					variationSelected: true,
					containerWidth: {
						value: 98,
						valueTablet: '',
						valueMobile: '',
						valueUnit: '%',
						valueUnitTablet: '',
						valueUnitMobile: '',
					},
					floatAlignment: {
						value: '',
						valueTablet: '',
						valueMobile: '',
					},
					floatMargin: {
						isLinked: true,
						isLinkedTablet: true,
						isLinkedMobile: true,
						common: '',
						top: '',
						right: '',
						bottom: '',
						left: '',
						unit: 'px',
						commonTablet: '',
						topTablet: '',
						rightTablet: '',
						bottomTablet: '',
						leftTablet: '',
						unitTablet: '',
						commonMobile: '',
						topMobile: '',
						rightMobile: '',
						bottomMobile: '',
						leftMobile: '',
						unitMobile: '',
					},
				},
				[
					[
						'ablocks/academy-container',
						{
							variationSelected: true,
							containerWidth: {
								value: 99,
								valueUnit: '%',
								valueTablet: '',
								valueMobile: '',
								valueUnitTablet: '',
								valueUnitMobile: '',
							},
							floatAlignment: {
								value: '',
								valueTablet: '',
								valueMobile: '',
							},
							floatMargin: {
								isLinked: true,
								isLinkedTablet: true,
								isLinkedMobile: true,
								common: '',
								top: '',
								right: '',
								bottom: '',
								left: '',
								unit: 'px',
								commonTablet: '',
								topTablet: '',
								rightTablet: '',
								bottomTablet: '',
								leftTablet: '',
								unitTablet: '',
								commonMobile: '',
								topMobile: '',
								rightMobile: '',
								bottomMobile: '',
								leftMobile: '',
								unitMobile: '',
							},
						},
					],
				],
			],
			[
				'ablocks/academy-container',
				{
					variationSelected: true,
					containerWidth: {
						value: 98,
						valueTablet: '',
						valueMobile: '',
						valueUnit: '%',
						valueUnitTablet: '',
						valueUnitMobile: '',
					},
					floatAlignment: {
						value: '',
						valueTablet: '',
						valueMobile: '',
					},
					floatMargin: {
						isLinked: true,
						isLinkedTablet: true,
						isLinkedMobile: true,
						common: '',
						top: '',
						right: '',
						bottom: '',
						left: '',
						unit: 'px',
						commonTablet: '',
						topTablet: '',
						rightTablet: '',
						bottomTablet: '',
						leftTablet: '',
						unitTablet: '',
						commonMobile: '',
						topMobile: '',
						rightMobile: '',
						bottomMobile: '',
						leftMobile: '',
						unitMobile: '',
					},
				},
				[
					[
						'ablocks/academy-container',
						{
							variationSelected: true,
							containerWidth: {
								value: 99,
								valueUnit: '%',
								valueTablet: '',
								valueMobile: '',
								valueUnitTablet: '',
								valueUnitMobile: '',
							},
							floatAlignment: {
								value: '',
								valueTablet: '',
								valueMobile: '',
							},
							floatMargin: {
								isLinked: true,
								isLinkedTablet: true,
								isLinkedMobile: true,
								common: '',
								top: '',
								right: '',
								bottom: '',
								left: '',
								unit: 'px',
								commonTablet: '',
								topTablet: '',
								rightTablet: '',
								bottomTablet: '',
								leftTablet: '',
								unitTablet: '',
								commonMobile: '',
								topMobile: '',
								rightMobile: '',
								bottomMobile: '',
								leftMobile: '',
								unitMobile: '',
							},
						},
					],
				],
			],
			[
				'ablocks/academy-container',
				{
					variationSelected: true,
					containerWidth: {
						value: 98,
						valueTablet: '',
						valueMobile: '',
						valueUnit: '%',
						valueUnitTablet: '',
						valueUnitMobile: '',
					},
					floatAlignment: {
						value: '',
						valueTablet: '',
						valueMobile: '',
					},
					floatMargin: {
						isLinked: true,
						isLinkedTablet: true,
						isLinkedMobile: true,
						common: '',
						top: '',
						right: '',
						bottom: '',
						left: '',
						unit: 'px',
						commonTablet: '',
						topTablet: '',
						rightTablet: '',
						bottomTablet: '',
						leftTablet: '',
						unitTablet: '',
						commonMobile: '',
						topMobile: '',
						rightMobile: '',
						bottomMobile: '',
						leftMobile: '',
						unitMobile: '',
					},
				},
				[
					[
						'ablocks/academy-container',
						{
							variationSelected: true,
							containerWidth: {
								value: 99,
								valueUnit: '%',
								valueTablet: '',
								valueMobile: '',
								valueUnitTablet: '',
								valueUnitMobile: '',
							},
							floatAlignment: {
								value: '',
								valueTablet: '',
								valueMobile: '',
							},
							floatMargin: {
								isLinked: true,
								isLinkedTablet: true,
								isLinkedMobile: true,
								common: '',
								top: '',
								right: '',
								bottom: '',
								left: '',
								unit: 'px',
								commonTablet: '',
								topTablet: '',
								rightTablet: '',
								bottomTablet: '',
								leftTablet: '',
								unitTablet: '',
								commonMobile: '',
								topMobile: '',
								rightMobile: '',
								bottomMobile: '',
								leftMobile: '',
								unitMobile: '',
							},
						},
					],
				],
			],
		],
		scope: [ 'block' ],
	},
];
