import { __ } from '@wordpress/i18n';

const status = {
	publish: 'publish',
	dev: 'dev',
	coming: 'coming',
	pro: 'pro',
};

export const coreBlockLists = [
	{
		icon: 'block-container',
		name: 'container',
		label: __( 'Container', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: false,
		status: status.publish,
	},
	{
		icon: 'block-heading',
		name: 'heading',
		label: __( 'Heading', 'ablocks' ),
		liveDemoUrl: 'https://ablocks.pro/heading/',
		allowInactive: false,
		status: status.publish,
	},
	{
		icon: 'block-paragraph',
		name: 'paragraph',
		label: __( 'Paragraph', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: false,
		status: status.publish,
	},
	{
		icon: 'block-icon',
		name: 'icon',
		label: __( 'Icon', 'ablocks' ),
		liveDemoUrl: 'https://ablocks.pro/icon/',
		allowInactive: false,
		status: status.publish,
	},
	{
		icon: 'block-button',
		name: 'button',
		label: __( 'Button', 'ablocks' ),
		liveDemoUrl: 'https://ablocks.pro/button/',
		allowInactive: false,
		status: status.publish,
	},
	{
		icon: 'block-button',
		name: 'dual-button',
		label: __( 'Dual Button', 'ablocks' ),
		liveDemoUrl: 'https://ablocks.pro/ablocks.pro/dual-button/',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'block-image',
		name: 'image',
		label: __( 'Image', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: false,
		status: status.publish,
	},
	{
		icon: 'block-spacer',
		name: 'spacer',
		label: __( 'spacer', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'block-star',
		name: 'star-ratings',
		label: __( 'Star Ratings', 'ablocks' ),
		liveDemoUrl: 'https://ablocks.pro/star-ratings/',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'block-divider',
		name: 'divider',
		label: __( 'Divider', 'ablocks' ),
		liveDemoUrl: 'https://ablocks.pro/divider/',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'block-counter',
		name: 'counter',
		label: __( 'Counter', 'ablocks' ),
		liveDemoUrl: 'https://ablocks.pro/counter/',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'block-countdown',
		name: 'countdown',
		label: __( 'Countdown', 'ablocks' ),
		liveDemoUrl: 'https://ablocks.pro/countdown/',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'modal',
		name: 'modal',
		label: __( 'Modal', 'ablocks' ),
		liveDemoUrl: 'https://ablocks.pro/modal/',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'block-video',
		name: 'video',
		label: __( 'Video', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'block-list',
		name: 'lists',
		label: __( 'List', 'ablocks' ),
		liveDemoUrl: 'https://ablocks.pro/list/',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'block-list',
		name: 'advance-lists',
		label: __( 'Advance lists', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'block-toggle',
		name: 'toggle',
		label: __( 'Toggle', 'ablocks' ),
		liveDemoUrl: 'https://ablocks.pro/ablocks.pro/toggle/',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'block-accordion',
		name: 'accordion',
		label: __( 'Accordion', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'block-tab',
		name: 'tabs',
		label: __( 'Tabs', 'ablocks' ),
		liveDemoUrl: 'https://ablocks.pro/tabs/',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'map',
		name: 'map',
		label: __( 'Map', 'ablocks' ),
		liveDemoUrl: 'https://ablocks.pro/map-blocks/',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'block-flipbox',
		name: 'flip-box',
		label: __( 'Flip Box', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'table-of-content',
		name: 'table-of-content',
		label: __( 'Table Of Contents', 'ablocks' ),
		liveDemoUrl: 'https://ablocks.pro/table-of-contents/',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'social-share',
		name: 'social-shares',
		label: __( 'Social Share', 'ablocks' ),
		liveDemoUrl: 'https://ablocks.pro/social-shares/',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'image-comparison',
		name: 'image-comparison',
		label: __( 'Image Comparison', 'ablocks' ),
		liveDemoUrl: 'https://ablocks.pro/image-comparison/',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'search',
		name: 'search',
		label: __( 'Search', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'notification',
		name: 'notice',
		label: __( 'Notification', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'block-carousel',
		name: 'carousel',
		label: __( 'Carousel', 'ablocks' ),
		liveDemoUrl: 'https://ablocks.pro/carousel/',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'table',
		name: 'table',
		label: __( 'Table', 'ablocks' ),
		liveDemoUrl: 'https://ablocks.pro/table-3/',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'block-icon',
		name: 'svg-draw',
		label: __( 'SVG Draw', 'ablocks' ),
		liveDemoUrl: 'https://ablocks.pro/svg-draw/',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'chart',
		name: 'chart',
		label: __( 'Chart', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'info-box',
		name: 'info-box',
		label: __( 'Info Box', 'ablocks' ),
		liveDemoUrl: 'https://ablocks.pro/info-box/',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'block-timeline',
		name: 'content-timeline',
		label: __( 'Content Timeline', 'ablocks' ),
		liveDemoUrl: 'https://ablocks.pro/content-timeline/',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'block-coupon',
		name: 'coupon',
		label: __( 'Coupon', 'ablocks' ),
		liveDemoUrl: 'https://ablocks.pro/coupon/',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'menu',
		name: 'menu',
		label: __( 'Menu', 'ablocks' ),
		liveDemoUrl: 'https://ablocks.pro/navigation-menu/',
		allowInactive: true,
	},
	{
		icon: `price-menu`,
		name: 'price-menu',
		label: __( 'Price Menu', 'ablocks' ),
		liveDemoUrl: 'https://ablocks.pro/menu-price/',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: `filterable-card`,
		name: 'filterable-card',
		label: __( 'Filterable Cards', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'loop-builder',
		name: 'loop-builder',
		label: __( 'Loop Builder', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'form-builder',
		name: 'form-builder',
		label: __( 'Form Builder', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'progress-bar',
		name: 'progress-tracker',
		label: __( 'Progress Tracker', 'ablocks' ),
		liveDemoUrl: 'https://ablocks.pro/progress-tracker/',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'log-out',
		name: 'logout',
		label: __( 'Logout', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'image-hotspot',
		name: 'image-hotspot',
		label: __( 'Image Hotspot', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'image-scroll',
		name: 'image-scroll',
		label: __( 'Image Scroll', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'image',
		name: 'featured-image',
		label: __( 'Featured Image', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'paypal',
		name: 'paypal-button',
		label: __( 'Paypal Button', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'news-ticker',
		name: 'news-ticker',
		label: __( 'News Ticker', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'stripe',
		name: 'stripe-button',
		label: __( 'Stripe Button', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'code-highlight',
		name: 'code-highlighter',
		label: __( 'Code Highlighter', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
		isPro: true,
	},
	{
		icon: 'in-dev',
		name: 'group-image-effect',
		label: __( 'Group Image Effect', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
		isPro: true,
	},
	{
		icon: 'stacked-cards',
		name: 'stacked-cards',
		label: __( 'Stacked Cards', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
		isPro: true,
	},
	{
		icon: 'frontend-dashboard',
		name: 'frontend-dashboard',
		label: __( 'Frontend Dashboard', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'marquee',
		name: 'marquee',
		label: __( 'Marquee Block', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'text-path',
		name: 'text-path',
		label: __( 'Text Path', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'player',
		name: 'player',
		label: __( 'player', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'lottie-animation',
		name: 'lottie-animation',
		label: __( 'Lottie Animation', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'taxonomy-listing',
		name: 'taxonomy-listing',
		label: __( 'Taxonomy Listing', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'qr-code',
		name: 'qr-code',
		label: __( 'QR Code', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'back-to-top',
		name: 'scroll-to-top',
		label: __( 'Scroll To Top', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'angle-right',
		name: 'breadcrumb',
		label: __( 'Breadcrumb', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'dynamic-text',
		name: 'dynamic-text',
		label: __( 'Dynamic Text', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
];

export const academyLMSBlockLists = [
	{
		icon: 'academy-lms',
		name: 'academy-courses',
		label: __( 'Course Grid', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'academy-lms',
		name: 'academy-login-form',
		label: __( 'Login Form', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'academy-lms',
		name: 'academy-enroll-form',
		label: __( 'Enroll Form', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'academy-lms',
		name: 'academy-student-registration-form',
		label: __( 'Student Reg. Form', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'academy-lms',
		name: 'academy-instructor-registration-form',
		label: __( 'Instructor Reg. Form', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'academy-lms',
		name: 'academy-course-search',
		label: __( 'Course Search', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'academy-lms',
		name: 'academy-pdf',
		label: __( 'PDF Embed', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'academy-lms',
		name: 'academy-password-reset-form',
		label: __( 'Password Reset Form', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'academy-lms',
		name: 'academy-certificate',
		label: __( 'Certificate Builder', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'academy-lms',
		name: 'academy-course-media',
		label: __( 'Academy Course Media', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'academy-lms',
		name: 'academy-course-curriculums',
		label: __( 'Academy Course Curriculums', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'academy-lms',
		name: 'academy-course-reviews',
		label: __( 'Academy Course Reviews', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'academy-lms',
		name: 'academy-review-form',
		label: __( 'Academy Reviews Form', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'academy-lms',
		name: 'academy-review-list',
		label: __( 'Academy Reviews List', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'academy-lms',
		name: 'academy-addition-info',
		label: __( 'Academy Addition Info', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'academy-lms',
		name: 'academy-course-instructor',
		label: __( 'Academy Course Instructor', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'academy-lms',
		name: 'academy-course-description',
		label: __( 'Academy Course Description', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'academy-lms',
		name: 'academy-enroll-content',
		label: __( 'Academy Enroll Content', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
];

export const storeEngineBlockLists = [
	{
		icon: 'storeengine',
		name: 'storeengine-products',
		label: __( 'StoreEngine Products', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'storeengine',
		name: 'storeengine-cart-list',
		label: __( 'StoreEngine Cart List', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'storeengine',
		name: 'storeengine-login-form',
		label: __( 'StoreEngine Login Form', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'storeengine',
		name: 'storeengine-coupon-form',
		label: __( 'StoreEngine Coupon Form', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'storeengine',
		name: 'storeengine-product-filter',
		label: __( 'StoreEngine Product Filter', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'storeengine',
		name: 'storeengine-checkout-form',
		label: __( 'StoreEngine Checkout From', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'storeengine',
		name: 'storeengine-continue-button',
		label: __( 'StoreEngine Continue Button', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'storeengine',
		name: 'storeengine-order-details',
		label: __( 'StoreEngine Order Derails', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'storeengine',
		name: 'storeengine-checkout-button',
		label: __( 'StoreEngine Checkout Button', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'storeengine',
		name: 'storeengine-cart-sub-table',
		label: __( 'StoreEngine Cart Sub Table', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'storeengine',
		name: 'storeengine-cart-button',
		label: __( 'StoreEngine Add To Cart', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'storeengine',
		name: 'storeengine-order-info',
		label: __( 'StoreEngine Order Info', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'storeengine',
		name: 'storeengine-billing-info',
		label: __( 'StoreEngine Billing Info', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'storeengine',
		name: 'storeengine-shipping-info',
		label: __( 'StoreEngine Shipping Info', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'storeengine',
		name: 'storeengine-mini-cart',
		label: __( 'StoreEngine Mini Cart Button', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'storeengine',
		name: 'storeengine-product-gallery',
		label: __( 'StoreEngine Product Gallery', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'storeengine',
		name: 'storeengine-product-summary',
		label: __( 'StoreEngine Product Summary', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'storeengine',
		name: 'storeengine-product-description',
		label: __( 'StoreEngine Product Description', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'storeengine',
		name: 'storeengine-product-review',
		label: __( 'StoreEngine Product Review', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
	{
		icon: 'storeengine',
		name: 'storeengine-cart-notice',
		label: __( 'StoreEngine Cart Notice', 'ablocks' ),
		liveDemoUrl: '#',
		allowInactive: true,
		status: status.publish,
	},
];
